### ISSUE TITLE
ConsoleKit2 opens sessions but ck-list-sessions claims they remain open after exit, logout, etc

### ISSUE THREAD

**Issue by chrisb2244** [ConsoleKit2/ConsoleKit2#27] opened 2015-07-01 07:02 UTC
Have installed:
PAM, ConsoleKit2, KDE(5), Polkit (and assorted polkit-qt-..., kde-polkit-...)

Do not have:
systemd, logind

I suspect my pam.d entries are to blame for the spawning of spurious ck-sessions, but with the most recent ConsoleKit(1) version, I'd typically end up with 1 or 2 sessions, and was fighting to try get to one, local/active session.

Installed ConsoleKit2 from origin/master and now my sessions are all `ACTIVE=false/is-local=TRUE` but relogging in and out, or closing the X-server and restarting it using `init 3; init 5` produces a new pair/set of sessions, and the old sessions never close for me.

Example output of `ck-list-sessions`:
```
Session3:
        unix-user = '0'
        realname = 'root'
        seat = 'Seat1'
        session-type = ''
        active = FALSE
        x11-display = ''
        x11-display-device = ''
        display-device = '/dev/tty1'
        remote-host-name = ''
        is-local = TRUE
        on-since = '2015-07-01T06:00:10.912382Z'
        login-session-id = '2'
Session4:
        unix-user = '1000'
        realname = 'Christian'
        seat = 'Seat1'
        session-type = ''
        active = FALSE
        x11-display = ''
        x11-display-device = ''
        display-device = '/dev/tty1'
        remote-host-name = ''
        is-local = TRUE
        on-since = '2015-07-01T06:00:36.176981Z'
        login-session-id = '3'
Session2:
        unix-user = '1000'
        realname = 'Christian'
        seat = 'Seat1'
        session-type = ''
        active = FALSE
        x11-display = ''
        x11-display-device = ''
        display-device = '/dev/tty1'
        remote-host-name = ''
        is-local = TRUE
        on-since = '2015-07-01T06:00:01.024415Z'
        login-session-id = '1'
Session1:
        unix-user = '64'
        realname = 'SDDM Daemon Owner'
        seat = 'Seat2'
        session-type = ''
        active = FALSE
        x11-display = ':0'
        x11-display-device = ''
        display-device = ''
        remote-host-name = ''
        is-local = TRUE
        on-since = '2015-07-01T05:59:45.428500Z'
        login-session-id = '4294967295'
Session5:
        unix-user = '1000'
        realname = 'Christian'
        seat = 'Seat3'
        session-type = ''
        active = FALSE
        x11-display = ':0'
        x11-display-device = ''
        display-device = ''
        remote-host-name = ''
        is-local = TRUE
        on-since = '2015-07-01T06:01:42.107570Z'
        login-session-id = '4'
Session6:
        unix-user = '1000'
        realname = 'Christian'
        seat = 'Seat4'
        session-type = ''
        active = FALSE
        x11-display = ':0'
        x11-display-device = '/dev/tty7'
        display-device = ''
        remote-host-name = ''
        is-local = TRUE
        on-since = '2015-07-01T06:01:42.747933Z'
        login-session-id = '4'
Session7:
        unix-user = '0'
        realname = 'root'
        seat = 'Seat5'
        session-type = ''
        active = FALSE
        x11-display = ''
        x11-display-device = ''
        display-device = '/dev/tty1'
        remote-host-name = ''
        is-local = FALSE
        on-since = '2015-07-01T06:51:42.816222Z'
        login-session-id = '5'
Session8:
        unix-user = '64'
        realname = 'SDDM Daemon Owner'
        seat = 'Seat6'
        session-type = ''
        active = FALSE
        x11-display = ':0'
        x11-display-device = ''
        display-device = ''
        remote-host-name = ''
        is-local = TRUE
        on-since = '2015-07-01T06:51:56.130420Z'
        login-session-id = '4294967295'
Session9:
        unix-user = '1000'
        realname = 'Christian'
        seat = 'Seat7'
        session-type = ''
        active = FALSE
        x11-display = ':0'
        x11-display-device = ''
        display-device = ''
        remote-host-name = ''
        is-local = TRUE
        on-since = '2015-07-01T06:52:00.176112Z'
        login-session-id = '6'
Session10:
        unix-user = '1000'
        realname = 'Christian'
        seat = 'Seat8'
        session-type = ''
        active = FALSE
        x11-display = ':0'
        x11-display-device = '/dev/tty7'
        display-device = ''
        remote-host-name = ''
        is-local = TRUE
        on-since = '2015-07-01T06:52:00.218515Z'
        login-session-id = '6'
```

My understanding is that 'sddm-greeter' should connect to the ConsoleKit daemon first, 'Session1' above, and that when I log in, it should use the `OpenSessionWithParameters` call to open a session for me with the daemon.

My pam files are :

sddm:
```
#%PAM-1.0
auth		include		system-auth
account		include		system-account
password	include		system-password

# Connect manually to the ConsoleKit daemon, since system-session is nox11
session         optional        pam_loginuid.so
session         optional        pam_ck_connector.so
session         include         system-session
```

sddm-greeter:
```
#%PAM-1.0
# Load environment from /etc/environment and ~/.pam_environment
auth		required pam_env.so
# Always let the greeter start without authentication
auth		required pam_permit.so
# No action required for account management
account		required pam_permit.so
# Can't change password
password	required pam_deny.so
# Setup session
# Connect to the system ConsoleKit daemon (this is the login screen)
session		optional pam_ck_connector.so
session		required pam_unix.so
```

system-session:
```
# Begin /etc/pam.d/system-session

session   required	pam_unix.so
session   optional	pam_loginuid.so

# If not a graphical session, then connects to the ConsoleKit daemon.
# This will occur for example with 'login'
#session	  optional	pam_ck_connector.so nox11
# Commenting out, since doesn't seem to close the sessions :/

# End /etc/pam.d/system-session
```

login: (as an example)
```
#%PAM-1.0

# Begin /etc/pam.d/login

# Set failure delay before next prompt to 2 seconds
auth      optional    pam_faildelay.so  delay=2000000

# Check to make sure that the user is allowed to login
auth      requisite   pam_nologin.so

# Check to make sure that root is allowed to login
# Disabled by default. You will need to create /etc/securetty
# file for this module to function. See man 5 securetty.
#auth      required    pam_securetty.so

# include the default auth settings
auth      include     system-auth

# check access for the user
account   required    pam_access.so
# include the default account settings
account   include     system-account

# Set default environment variables for the user
session   required    pam_env.so
# Set resource limits for the user
#session   required    pam_limits.so

# include the default session and password settings
session   include     system-session

password  include     system-password

# End /etc/pam.d/login
```

Did I do something wrong, or is this a bug causing the sessions to not close?
(Note, I'm sure all the ACTIVE/is-local problems are caused by my poor setup, but I'm less sure that the ck-list-sessions throwing a bunch of entries is due to pam)

**Comment by xtraeme** [comment] 2015-07-02 06:35
I can also reproduce the same behaviour with ConsoleKit2-0.9.4.

Sessions are active=FALSE and is-local=TRUE, and old sessions aren't destroyed anymore. Seems to be a regression introduced in 0.9.3.

**Comment by chrisb2244** [comment] 2015-07-02 06:54
I got the same behaviour with the (git) 0.9.3 release. Perhaps I checked it out wrong?

```
make distclean
git checkout 0.9.3
./autogen.sh <long list of parameters/arguments>
make -j16
sudo make install
```

followed by

```
init 1; 
< type root password to avoid killing system >
init 5; 
<login using sddm>
ck-list-sessions (1 session, is-local=TRUE, Active=False); 
ck-launch-session ck-list-sessions (2 sessions, as expected); 
<repeat last step, 3 sessions, unexpected>
```

**Comment by chrisb2244** [comment] 2015-07-02 06:57
For the sake of further description, with the 0.9.3 git version, I have 
```
Session<N>:
        unix-user = '1000'
        realname = 'Christian'
        seat = 'Seat<N+1>'
        session-type = ''
        active = FALSE
        x11-display = ':0'
        x11-display-device = '/dev/tty7'
        display-device = '/dev/pts/0'
        remote-host-name = ''
        is-local = TRUE
        on-since = '2015-07-02T06:51:41.638236Z'
        login-session-id = '9'
        idle-since-hint = '1970-01-01T00:00:00Z'
```

and 

```
Session1:
        unix-user = '1000'
        realname = 'Christian'
        seat = 'Seat2'
        session-type = ''
        active = FALSE
        x11-display = ':0'
        x11-display-device = ''
        display-device = ''
        remote-host-name = ''
        is-local = TRUE
        on-since = '2015-07-02T06:50:55.443272Z'
        login-session-id = '9'
        idle-since-hint = '1970-01-01T00:00:00Z'
``` 
i.e. no `x11-display-device`, no `display-device`, also no `session-type`, but that is true for subsequently launched sessions also.

**Comment by xtraeme** [comment] 2015-07-02 06:57
It's a regression introduced in 0.9.3. somehow it was ok with 0.9.2 some days before 0.9.3 was released.

In voidlinux we are still using 0.9.2 + patches before 0.9.3 was released and it works as expected.

**Comment by chrisb2244** [comment] 2015-07-02 06:58
Will try 0.9.2 then, and report back

**Comment by chrisb2244** [comment] 2015-07-02 07:08
Can confirm that the 0.9.2 git marker removes ending sessions.
After several repeats of `ck-launch-session ck-list-sessions` I get (as expected):
```
Session7:
        unix-user = '1000'
        realname = 'Christian'
        seat = 'Seat1'
        session-type = ''
        active = TRUE
        x11-display = ':0'
        x11-display-device = '/dev/tty7'
        display-device = '/dev/pts/0'
        remote-host-name = ''
        is-local = TRUE
        on-since = '2015-07-02T07:07:33.172268Z'
        login-session-id = '11'
Session1:
        unix-user = '1000'
        realname = 'Christian'
        seat = 'Seat2'
        session-type = ''
        active = FALSE
        x11-display = ':0'
        x11-display-device = ''
        display-device = ''
        remote-host-name = ''
        is-local = TRUE
        on-since = '2015-07-02T07:06:30.402303Z'
        login-session-id = '11'
```

Here, can see that the sessions appearing on 'Seat1' created by ck-launch-session are both active and local. The 'Session1' remains inactive, but I'm fairly confident this is a pam/sddm configuration issue.

Should I try bisect and find the patch? Or are the changes too big?

**Comment by xtraeme** [comment] 2015-07-02 07:17
Would be nice if you can bisect it, I'd also be interested to know where's the regression.

**Comment by chrisb2244** [comment] 2015-07-02 07:57
So `git bisect` informs me that the first bad commit is `commit 0a968ab04d8a5dc87f352294a6c9b099c5abda2a`. 

It's possibly worth noting that although I marked the commit before that as good (since it did remove sessions, and left me with only the two I expected), it did spew a bunch of messages like: (commit `f6a7cca`)

```
** (ck-list-sessions:27036): WARNING **: GetUnixUser failed: Method "GetUnixUser" with signature "" on interface "org.freedesktop.ConsoleKit.Session" doesn't exist

** (ck-list-sessions:27036): WARNING **: GetSeatId failed: Method "GetSeatId" with signature "" on interface "org.freedesktop.ConsoleKit.Session" doesn't exist

** (ck-list-sessions:27036): WARNING **: GetLoginSessionId failed: Method "GetLoginSessionId" with signature "" on interface "org.freedesktop.ConsoleKit.Session" doesn't exist

** (ck-list-sessions:27036): WARNING **: GetSessionType failed: Method "GetSessionType" with signature "" on interface "org.freedesktop.ConsoleKit.Session" doesn't exist

** (ck-list-sessions:27036): WARNING **: GetX11Display failed: Method "GetX11Display" with signature "" on interface "org.freedesktop.ConsoleKit.Session" doesn't exist

** (ck-list-sessions:27036): WARNING **: GetX11DisplayDevice failed: Method "GetX11DisplayDevice" with signature "" on interface "org.freedesktop.ConsoleKit.Session" doesn't exist

** (ck-list-sessions:27036): WARNING **: GetDisplayDevice failed: Method "GetDisplayDevice" with signature "" on interface "org.freedesktop.ConsoleKit.Session" doesn't exist

** (ck-list-sessions:27036): WARNING **: GetRemoteHostName failed: Method "GetRemoteHostName" with signature "" on interface "org.freedesktop.ConsoleKit.Session" doesn't exist

** (ck-list-sessions:27036): WARNING **: IsActive failed: Method "IsActive" with signature "" on interface "org.freedesktop.ConsoleKit.Session" doesn't exist

** (ck-list-sessions:27036): WARNING **: IsLocal failed: Method "IsLocal" with signature "" on interface "org.freedesktop.ConsoleKit.Session" doesn't exist

** (ck-list-sessions:27036): WARNING **: GetCreationTime failed: Method "GetCreationTime" with signature "" on interface "org.freedesktop.ConsoleKit.Session" doesn't exist

** (ck-list-sessions:27036): WARNING **: GetIdleSinceHint failed: Method "GetIdleSinceHint" with signature "" on interface "org.freedesktop.ConsoleKit.Session" doesn't exist

(ck-list-sessions:27036): GLib-CRITICAL **: g_str_has_prefix: assertion 'str != NULL' failed
Session5:
        unix-user = '24641422'
        realname = '(null)'
        seat = '(null)'
        session-type = '(null)'
        active = FALSE
        x11-display = '(null)'
        x11-display-device = '(null)'
        display-device = '(null)'
        remote-host-name = '(null)'
        is-local = TRUE
        on-since = '(null)'
        login-session-id = '(null)'

< All the same warnings>
(ck-list-sessions:27036): GLib-CRITICAL **: g_str_has_prefix: assertion 'str != NULL' failed
Session1:
        unix-user = '24641422'
        realname = '(null)'
        seat = '(null)'
        session-type = '(null)'
        active = FALSE
        x11-display = '(null)'
        x11-display-device = '(null)'
        display-device = '(null)'
        remote-host-name = '(null)'
        is-local = TRUE
        on-since = '(null)'
        login-session-id = '(null)'

```

and obviously all the fields are marked as 'null', so 'good' is possibly a stretch.

I had to skip several commits since they wouldn't build for me - they were during the conversion to GDBus, so possibly not too surprising.

Output of `git bisect log`
```
git bisect start
# bad: [b61e060a0f1ce23cb27d41a075ec0e38c857d55f] trivial: updates for release
git bisect bad b61e060a0f1ce23cb27d41a075ec0e38c857d55f
# good: [fb6de51e6acdd7cc3a9f4c9c1c9746eb20aeef26] trivial: updates for release
git bisect good fb6de51e6acdd7cc3a9f4c9c1c9746eb20aeef26
# bad: [52a6fbe1ae8e9cf8f4326eca75f3568dab89e0f7] Always return TRUE from dbus calls
git bisect bad 52a6fbe1ae8e9cf8f4326eca75f3568dab89e0f7
# bad: [52a6fbe1ae8e9cf8f4326eca75f3568dab89e0f7] Always return TRUE from dbus calls
git bisect bad 52a6fbe1ae8e9cf8f4326eca75f3568dab89e0f7
# good: [759882633b07ac8f5191cf70361bb0a6f03f6678] Merge pull request #22 from fluxer/master
git bisect good 759882633b07ac8f5191cf70361bb0a6f03f6678
# bad: [89e5d40ba8bfca9b8cb152251de1373d12f7da8e] Use g_hash_table_get_keys_as_array to get the id
git bisect bad 89e5d40ba8bfca9b8cb152251de1373d12f7da8e
# skip: [8f4fe327e3e657a4b745e242615ba1d281cdd4d0] Start removing dbus dependencies
git bisect skip 8f4fe327e3e657a4b745e242615ba1d281cdd4d0
# skip: [8f4fe327e3e657a4b745e242615ba1d281cdd4d0] Start removing dbus dependencies
git bisect skip 8f4fe327e3e657a4b745e242615ba1d281cdd4d0
# skip: [2fde17d8a3f06717b47ccb392d1d1c3b5c8eaa72] Minor fixes
git bisect skip 2fde17d8a3f06717b47ccb392d1d1c3b5c8eaa72
# skip: [b053cf1d055ffeb6fbb4d3e2225744d60b21ddef] Port CkManager to GDBus
git bisect skip b053cf1d055ffeb6fbb4d3e2225744d60b21ddef
# skip: [f782a76b94da1e69a2c3ae5441ed8b953dbb8316] Port ck-session-leader to GDBus
git bisect skip f782a76b94da1e69a2c3ae5441ed8b953dbb8316
# bad: [bdf3571ebec8a470282be9fd32572fd046c8c994] More GDBus work
git bisect bad bdf3571ebec8a470282be9fd32572fd046c8c994
# bad: [f9603918b4a92ad1c1e09550e5df0f95519fb6b0] More GDBus port work
git bisect bad f9603918b4a92ad1c1e09550e5df0f95519fb6b0
# bad: [f9603918b4a92ad1c1e09550e5df0f95519fb6b0] More GDBus port work
git bisect bad f9603918b4a92ad1c1e09550e5df0f95519fb6b0
# bad: [0a968ab04d8a5dc87f352294a6c9b099c5abda2a] CkSeat: Port to GDBus
git bisect bad 0a968ab04d8a5dc87f352294a6c9b099c5abda2a
# bad: [0a968ab04d8a5dc87f352294a6c9b099c5abda2a] CkSeat: Port to GDBus
git bisect bad 0a968ab04d8a5dc87f352294a6c9b099c5abda2a
# good: [f6a7ccad79f5fa55ed89b7ebdfe49b1888a9aa68] CKSession: Port to GDBus
git bisect good f6a7ccad79f5fa55ed89b7ebdfe49b1888a9aa68
# first bad commit: [0a968ab04d8a5dc87f352294a6c9b099c5abda2a] CkSeat: Port to GDBus
```

**Comment by EricKoegel** [comment] 2015-07-03 16:58
Yeah, looks like the new GDBus code isn't properly watching for the NameOwnerChanged message by DBus. https://github.com/EricKoegel/ConsoleKit2/commit/1dcab3fdb316499f6c33fe81bae488f2fde03039 should do that now but I don't have enough time to fully test it today. If someone could verify if it does or doesn't I'd appreciate it.

**Comment by chrisb2244** [comment] 2015-07-05 00:36
So the `gdbusconnection.h` header I have under `/opt/gnome/include/glib-2.0/gio/gdbusconnection.h` only has a `g_dbus_connection_signal_unsubscribe` taking two arguments. 

On line 3581 of the `./src/ck-manager.c` file, you call it will only one argument - it is missing a `guint subscription_id`. This gives me a build error.

Do I need a newer/older version of glib, or is this a problem with the ConsoleKit2 code?

**Comment by EricKoegel** [comment] 2015-07-05 04:09
Sorry about that, GCC didn't complain to me about it until I did a make clean. Odd. The additional patch is at https://github.com/EricKoegel/ConsoleKit2/commit/31aa29f778a765f9416ed8f3d2160321dab162b0 I'll squash them down if these commits fix the issue.

**Comment by chrisb2244** [comment] 2015-07-05 04:46
Certainly it builds successfully now. A quick test without restart made it look unchanged, but I suspect this is just because it's still running the old version. Unfortunately, I seem to have lost my connection to my workstation in the process of trying to remotely kill pieces. Will report tomorrow on the outcome

**Comment by chrisb2244** [comment] 2015-07-06 00:08
New commit to EricKoegel/watch-session-exit builds and runs successfully. The ended sessions are removed. The Sessions spawned are now 'active = false, is-local = true', but I suspect that that's another configuration error that I've managed to overwrite at some point. Thanks.

**Comment by EricKoegel** [comment] 2015-07-12 13:29
With the patch confirmed working and pushed to master I'm closing this issue. Thanks for pointing out the bug and confirming the patch works!

**Closed by EricKoegel** 2015-07-12 13:29 UTC
