### ISSUE TITLE
cgroups support not quite finished?

### ISSUE THREAD

**Issue by udeved** [ConsoleKit2/ConsoleKit2#42] opened 2015-08-21 15:19 UTC
console-kit-daemon[2677]: WARNING: Failed to let cgmanager know that it can remove the cgroup when it's empty, the error was: invalid request

Shouldn't /run/cgmanager/fs/ contain some stuff?
Its empty and only has cgroup controller folders.

I get this error logged on gentoo and on manjaro.

**Comment by EricKoegel** [comment] 2015-08-21 17:05
if you cat /proc/self/cgroup you should see something like 4:cpuacct:/org/freedesktop/ConsoleKit/Session2

**Comment by udeved** [comment] 2015-08-21 18:42
Will do.
Just have another problem, that cgmanager doesn't create a pid file on manjaro, its fine on gentoo and same box.

**Comment by udeved** [comment] 2015-08-21 18:58
With cgmanager started on manjaro, where cgmanager doesn't create pid on one out of my 3 test boxes.

cat /proc/self/cgroup
~~~
11:name=systemd:/
10:bfqio:/
9:net_cls:/
8:freezer:/
7:devices:/
6:memory:/
5:blkio:/
4:cpuacct:/
3:cpu:/
2:cpuset:/
1:name=openrc:/xdm
~~~

**Comment by EricKoegel** [comment] 2015-08-22 07:27
Well the warning you are seeing is harmless, I just thought it would be a good idea to let cgmanager clean up the cgroup once the session is gone but it's not like it takes up a ton of resources. Not too sure why you get an invalid request and I never do... but if you see the 4:cpuacct:/org/freede... stuff then everything is working as far as CK2 is concerned.

The first test box however is interesting. Does CK2 give any warnings at all? I tried to be detailed with the warning messages to help diagnose those kinds of errors. If nothing shows up then maybe CK2 was compiled before cgmanager was around or it didn't auto-detect properly in the configure script? --enable-debug=full will also cause CK2 to print out a lot of debug messages (and also crash on that/any warning message...)

**Comment by udeved** [comment] 2015-08-22 07:49
Thanks for the hint.
I will enable debug.

The situation is as follows.
I got my my dev system with gentoo an manjaro dual boot.
ck2 with cgroups runs fine on gentoo and in vbox from manjaro host.
Same for a test laptop with manjaro. It runs fine.
Now, on my dev box, I can't get the cgmanager to start with a pid file in /run, which I believe causes the problem of ck not properly adding session in cgroup.
I have currently no clue why this happens, as I freshly installed the manjaro.
All majaro boxes use the same packages, I myself compiled for the repo. Very strange.
Since the same runs on gentoo on same box, I would rule out some hardware cause, the kernel seems fine too, as it does it all in vbox and on laptop.

**Comment by udeved** [comment] 2015-08-22 16:32
Ok, I did some more tests, the mentioned laptop starts cgmanager with pid properly, but

~~~
$ cat /proc/self/cgroup
11:name=systemd:/
10:bfqio:/
9:net_cls:/
8:freezer:/
7:devices:/
6:memory:/
5:blkio:/
4:cpuacct:/
3:cpu:/
2:cpuset:/
1:name=openrc:/xdm
~~~

So this leaves on vbox tzo be working with manjaro, and gentoo on real hardware.

**Comment by EricKoegel** [comment] 2015-08-24 07:08
No warning messages from consolekit2 when cgmanager is working? I'll setup a physical manjaro machine to see if I can reproduce this issue. The good news is that if the cgmanager calls fail to return the proper ssid, CK2 will just fallback to the XDG_SESSION_COOKIE so everything continues to work. But it would be nice to see where the bug is and fix it (in CK2 or cgmanager).

**Comment by udeved** [comment] 2015-08-24 09:34
I have made some further testing, and I think its something permission problem with cgmanager.

I build an iso, started that iso from grub on my real dev box.
Result is, cgmanager starts and creates a pid file.
After I installed from the iso, cgmanager crashes and no pid file in /run..

**Comment by udeved** [comment] 2015-08-24 10:57
Here is some log and info on the test laptop with optimus nvidia.

Note, cgmanager starts properly on the machine, but a ck session is not in the cgroup.

~~~
laptop console-kit-daemon[1594]: WARNING: Failed to get the session id from cgmanager, the error was: Connection is closed
~~~

~~~
$ rc-status
Runlevel: default
 syslog-ng                                                                      [  started  ]
 lm_sensors                                                                     [  started  ]
 cronie                                                                         [  started  ]
 dbus                                                                           [  started  ]
 cgmanager                                                                      [  started  ]
 NetworkManager                                                                 [  started  ]
 netmount                                                                       [  started  ]
 consolekit                                                                     [  started  ]
 xdm                                                                            [  started  ]
 bluetooth                                                                      [  started  ]
 bumblebee                                                                      [  started  ]
 acpid                                                                          [  started  ]
 cupsd                                                                          [  started  ]
 saned                                                                          [  started  ]
 local                                                                          [  started  ]
Dynamic Runlevel: hotplugged
Dynamic Runlevel: needed
 lvmetad                                                                        [  started  ]
 xdm-setup                                                                      [  started  ]
 avahi-daemon                                                                   [  started  ]
 vgl                                                                            [  started  ]
Dynamic Runlevel: manual
~~~

~~~
$ cat /proc/self/cgroup
11:name=systemd:/
10:bfqio:/
9:net_cls:/
8:freezer:/
7:devices:/
6:memory:/
5:blkio:/
4:cpuacct:/
3:cpu:/
2:cpuset:/
1:name=openrc:/xdm
~~~

~~~
$ ls /run | grep cgm                                                   
cgmanager
cgmanager.pid
~~~

I would also like to get to the bottom of this. ;)

**Comment by udeved** [comment] 2015-08-25 23:37
I managed to upload a current iso build for testing.

http://sourceforge.net/projects/manjaro-lxqt-openrc/files/0.9.0-dev/manjaro-lxqt-minimal-openrc-0.9.0-x86_64.iso/download

**Comment by udeved** [comment] 2015-09-03 23:14
I did some more testing after the cgmanager issue was hopefully fixed.

Test on manjaro laptop.

using cgmanager-git

with lightdm
~~~
$ cat /proc/self/cgroup
11:name=systemd:/
10:bfqio:/
9:net_cls:/
8:freezer:/
7:devices:/
6:memory:/
5:blkio:/
4:cpuacct:/
3:cpu:/
2:cpuset:/
1:name=openrc:/xdm
~~~

with sddm:

~~~
$ cat /proc/self/cgroup
11:name=systemd:/
10:bfqio:/
9:net_cls:/
8:freezer:/
7:devices:/
6:memory:/
5:blkio:/
4:cpuacct:/org/freedesktop/ConsoleKit/Session1
3:cpu:/
2:cpuset:/
1:name=openrc:/xdm
~~~

But, still an error loged:
~~~
console-kit-daemon[1493]: WARNING: Failed to get the session id from cgmanager, the error was: Connection is closed
~~~

**Comment by udeved** [comment] 2015-09-06 16:54
The above test was on a bumblebee optimus laptop, where vgl runs.

Now, on my dev box with lightdm and after cgmanager fix:

~~~
$ cat /proc/self/cgroup
11:name=systemd:/
10:bfqio:/
9:net_cls:/
8:freezer:/
7:devices:/
6:memory:/
5:blkio:/
4:cpuacct:/org/freedesktop/ConsoleKit/Session2
3:cpu:/
2:cpuset:/
1:name=openrc:/xdm
~~~

Yay!

**Comment by EricKoegel** [comment] 2015-09-15 16:04
Hey! I've been busy the last week or so, sorry. Is it working now for all your systems?

**Comment by udeved** [comment] 2015-09-16 21:20
It works fine on both gentoo and manjaro.
I haven't had much time either to investigate, why it works with sddm on optimus manjaro laptop, but not with lightdm.

**Comment by Calrama** [comment] 2016-01-01 23:49
First, thanks for your work on ConsoleKit2. Second:
- Shouldn't the cgroup be created for all controllers (needed in order for cool things such as unprivileged LXC containers)? This just requires changing the three occurances of "cpuacct" in src/ctk-process-group.c to "all".
- Also required for unprivileged LXC containers: Shouldn't the cgroup be chown'ed to the logged in user?

**Comment by EricKoegel** [comment] 2016-01-11 16:00
I didn't include all of them because I didn't know if there was any performance drawback to adding everything but yeah, should be a trivial change and we can always expose it in a configuration file.
Yes, we should chown it to the user, I overlooked that, good catch!

**Comment by Calrama** [comment] 2016-02-02 01:12
Implemented my two points mentioned above in https://github.com/ConsoleKit2/ConsoleKit2/pull/61

**Comment by EricKoegel** [comment] 2016-02-08 11:56
Awesome, one question: If we do change ownership of the cgroup to the user couldn't they then add pids to the tasks file that they don't own and mislead CK2?

**Comment by Calrama** [comment] 2016-02-08 22:39
@EricKoegel While I could not find it being mentioned in the [kernel docs for cgroups, version 1](https://www.kernel.org/doc/Documentation/cgroup-v1/cgroups.txt), but [this lwn article about cgroups version 1](https://lwn.net/Articles/606699/)  mentions a
> suitably privileged user

and AFAIK the entire thing with cgroups is that unprivileged users can neither go (or affect things) up, nor sideways, only stay where they are, or go down the hierarchy. I could not find a proper source for this, but I'm fairly convinced that when I first read up about cgroups it was mentioned that (non-root) users may only move their own created processes and those only downwards in the hierarchy.
While not as good as a source backing that up, you can try
```bash
$ echo '1' > /sys/fs/cgroup/cpu/$(cat /proc/self/cgroup | grep -oP 'cpu:\K.*')/tasks
```
and should see it throwing
```bash
echo: write error: permission denied
```

while
```bash
$ echo $$ > /sys/fs/cgroup/cpu/$(cat /proc/self/cgroup | grep -oP 'cpu:\K.*')/tasks
```

succeeds; provided the shell you invoke this from is actually in some proper cgroup owned by the invoking user. I invoked the above commands in a graphical terminal emulator on the setup mentioned in the PR (with the PR's commits) to get the above results.

**Comment by EricKoegel** [comment] 2016-02-09 16:14
Thanks, just wanted to double-check. I merged your pull request, thank you.

**Comment by Calrama** [comment] 2016-02-09 16:25
Cool. One question: Is there still some functionality missing from ConsoleKit2 regarding cgroups? AFAIK this should be everything - it works for me (TM), anyway.

**Comment by EricKoegel** [comment] 2016-02-09 16:33
Yeah, I think you got everything, I'll close this report.

**Closed by EricKoegel** 2016-02-09 16:33 UTC
